---
title: "Assignment 8"
author: Artie Maharaj
date: April 6, 2020
output: html_notebook
---
This is my assignment 8 for EDRM 718

1. Write a function that will compute the total score for respondents on a Likert Scale

```{r}
Likert.Total.Score <- function(dataframe, numeric, vector) {
  
  #here is the function for the dataframe
  
  dataframe <-read.csv("data")
  
  #here is the function to call the number of scale items. 
  
  numeric = somenumber
  
  #here is the function for a numeric vector indicating which items should be reversed       scored
  
  new.data.frame <- dataframe
  
  new.data.frame[, c(qx,qy,qz)] <- x-new.data.frame[,c(qx,qy,qz)]
  
  #need to update the dataframe to reflect the updated reversed scored items. so this     
  #should just recode my scores in the dataframe. not sure if i need cbind here. 
  
  #need to sum total score across items
 total.scores <- rowSums(new.data.frame)
  
  
  return(total.scores)
 
}
```

2. This is the test of my function

```{r}

#code to run the dataframe

likert.data <- read.csv("art.data.csv")

likert.data= likert.data[-c(6),] 

#code to run the scale

numeric = 6

# function for to reverse code items Q2, Q4, Q7
new.likert.data <- likert.data
  
new.likert.data[,c(2, 4, 7)] <- abs(new.likert.data[,c(2, 4, 7)] -7)

#total scores for each respondent

total.scores <- rowSums(new.likert.data)

#add in new column to the new.likert.data dataframe.  
new.likert.data$total.scores


```

